# Generated by Django 4.1 on 2022-09-07 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='weather',
            field=models.CharField(default='No DATA', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(regex='(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{6,}$')]),
        ),
    ]
